---
title: "Developing Data Products Week 2 Assignment"
author: "Cherylyn Ee"
date: "19 October 2016"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Top 10 Places to Eat in Malacca, Malaysia
```{r, results = "hide", include = FALSE}
library(dplyr)
library(leaflet)
```

```{r, echo = FALSE, message = FALSE}
mlc_food <- data.frame(name = c("Portuguese Square Restaurant", "Teo Soon Loong Seafood Restaurant", "Ban Hong Xiang Tea House", "Awang Roti Canai", "Ban Lee Siang Satay Celup", "Tong Bee's Stall Shell Food", "Huang Chang Chicken Rice Restaurant", "Nancy's Kitchen", "Jonker 88", "Pak Putra"),
                        lat = c(2.183357,  2.197355,  2.214098,  2.240254,  2.204271,  2.199813,  2.239277,  2.197500,  2.196333,  2.194961),
                        lng = c(102.266321, 102.232130, 102.239536, 102.278428, 102.244667, 102.251660, 102.257999, 102.239695, 102.246974, 102.243838))
mlc_food$fdnm <- paste0("<p>",mlc_food$name,"<br />",mlc_food$lat,", ",mlc_food$lng,"</p>")
mlc_food %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers(popup = mlc_food$fdnm)
```


